import { config } from '@fortawesome/fontawesome-svg-core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';

import Providers from '@/components/providers';
import { cn } from '@/lib/styles';

import '@fortawesome/fontawesome-svg-core/styles.css';
import './tailwind.css';

const inter = Inter({ subsets: ['latin'] });
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'flex h-dvh w-full')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
